// Code generated by sqlc. DO NOT EDIT.
// Run `make generate` to regenerate.

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	LastLoginAt  *time.Time `json:"last_login_at"`
}

type RefreshToken struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	TokenHash  string     `json:"token_hash"`
	IssuedAt   time.Time  `json:"issued_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	ReplacedBy *uuid.UUID `json:"replaced_by"`
	UserAgent  *string    `json:"user_agent"`
	IPAddress  *string    `json:"ip_address"`
}

type PasswordResetToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	IssuedAt  time.Time  `json:"issued_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
}

type LoginAttempt struct {
	ID          uuid.UUID  `json:"id"`
	Email       string     `json:"email"`
	Success     bool       `json:"success"`
	IPAddress   *string    `json:"ip_address"`
	UserAgent   *string    `json:"user_agent"`
	AttemptedAt time.Time  `json:"attempted_at"`
}

type SigningKey struct {
	ID            uuid.UUID  `json:"id"`
	Kid           string     `json:"kid"`
	Algorithm     string     `json:"algorithm"`
	PrivateKeyPem string     `json:"private_key_pem"`
	PublicKeyPem  string     `json:"public_key_pem"`
	CreatedAt     time.Time  `json:"created_at"`
	ActivatedAt   time.Time  `json:"activated_at"`
	RetiredAt     *time.Time `json:"retired_at"`
	DeletedAt     *time.Time `json:"deleted_at"`
}

type Outbox struct {
	ID          uuid.UUID  `json:"id"`
	AggregateID uuid.UUID  `json:"aggregate_id"`
	EventType   string     `json:"event_type"`
	Payload     []byte     `json:"payload"`
	OccurredAt  time.Time  `json:"occurred_at"`
	PublishedAt *time.Time `json:"published_at"`
}
