// Code generated by sqlc. DO NOT EDIT.
// Run `make generate` to regenerate.

package db

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

type DBTX interface {
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

type Queries struct {
	db DBTX
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}

func NewFromPool(pool *pgxpool.Pool) *Queries {
	return &Queries{db: pool}
}

var _ Querier = (*Queries)(nil)

// ── Users ──────────────────────────────────────────────────────────────────

const createUser = `
INSERT INTO users (id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, created_at, updated_at, deleted_at, last_login_at`

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	return scanUser(row)
}

const getUserByID = `
SELECT id, email, password_hash, created_at, updated_at, deleted_at, last_login_at
FROM users WHERE id = $1 AND deleted_at IS NULL`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	return scanUser(row)
}

const getUserByEmail = `
SELECT id, email, password_hash, created_at, updated_at, deleted_at, last_login_at
FROM users WHERE email = $1 AND deleted_at IS NULL`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	return scanUser(row)
}

func scanUser(row pgx.Row) (User, error) {
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt, &u.UpdatedAt, &u.DeletedAt, &u.LastLoginAt)
	return u, err
}

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, `UPDATE users SET last_login_at = NOW(), updated_at = NOW() WHERE id = $1`, id)
	return err
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, `UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1`, arg.ID, arg.PasswordHash)
	return err
}

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, `UPDATE users SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1`, id)
	return err
}

// ── Refresh Tokens ─────────────────────────────────────────────────────────

const createRefreshToken = `
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at, user_agent, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, issued_at, expires_at, revoked_at, replaced_by, user_agent, ip_address`

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.ID, arg.UserID, arg.TokenHash, arg.ExpiresAt, arg.UserAgent, arg.IPAddress)
	return scanRefreshToken(row)
}

const getRefreshTokenByHash = `
SELECT id, user_id, token_hash, issued_at, expires_at, revoked_at, replaced_by, user_agent, ip_address
FROM refresh_tokens WHERE token_hash = $1`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	return scanRefreshToken(row)
}

func scanRefreshToken(row pgx.Row) (RefreshToken, error) {
	var t RefreshToken
	err := row.Scan(&t.ID, &t.UserID, &t.TokenHash, &t.IssuedAt, &t.ExpiresAt, &t.RevokedAt, &t.ReplacedBy, &t.UserAgent, &t.IPAddress)
	return t, err
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, `UPDATE refresh_tokens SET revoked_at = NOW(), replaced_by = $2 WHERE id = $1 AND revoked_at IS NULL`, arg.ID, arg.ReplacedBy)
	return err
}

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, `UPDATE refresh_tokens SET revoked_at = NOW() WHERE user_id = $1 AND revoked_at IS NULL`, userID)
	return err
}

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, `DELETE FROM refresh_tokens WHERE expires_at < NOW() - INTERVAL '30 days' OR revoked_at < NOW() - INTERVAL '30 days'`)
	return err
}

// ── Password Reset ─────────────────────────────────────────────────────────

const createPasswordResetToken = `
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, issued_at, expires_at, used_at`

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.ID, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var t PasswordResetToken
	err := row.Scan(&t.ID, &t.UserID, &t.TokenHash, &t.IssuedAt, &t.ExpiresAt, &t.UsedAt)
	return t, err
}

const getPasswordResetTokenByHash = `
SELECT id, user_id, token_hash, issued_at, expires_at, used_at FROM password_reset_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > NOW()`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var t PasswordResetToken
	err := row.Scan(&t.ID, &t.UserID, &t.TokenHash, &t.IssuedAt, &t.ExpiresAt, &t.UsedAt)
	return t, err
}

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, `UPDATE password_reset_tokens SET used_at = NOW() WHERE id = $1`, id)
	return err
}

// ── Signing Keys ───────────────────────────────────────────────────────────

const createSigningKey = `
INSERT INTO signing_keys (id, kid, algorithm, private_key_pem, public_key_pem, activated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, kid, algorithm, private_key_pem, public_key_pem, created_at, activated_at, retired_at, deleted_at`

func (q *Queries) CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRow(ctx, createSigningKey, arg.ID, arg.Kid, arg.Algorithm, arg.PrivateKeyPem, arg.PublicKeyPem)
	return scanSigningKey(row)
}

func (q *Queries) GetActiveSigningKey(ctx context.Context) (SigningKey, error) {
	row := q.db.QueryRow(ctx, `SELECT id, kid, algorithm, private_key_pem, public_key_pem, created_at, activated_at, retired_at, deleted_at FROM signing_keys WHERE retired_at IS NULL AND deleted_at IS NULL ORDER BY activated_at DESC LIMIT 1`)
	return scanSigningKey(row)
}

func (q *Queries) ListValidatingSigningKeys(ctx context.Context) ([]SigningKey, error) {
	rows, err := q.db.Query(ctx, `SELECT id, kid, algorithm, private_key_pem, public_key_pem, created_at, activated_at, retired_at, deleted_at FROM signing_keys WHERE deleted_at IS NULL ORDER BY activated_at DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var keys []SigningKey
	for rows.Next() {
		k, err := scanSigningKey(rows)
		if err != nil {
			return nil, err
		}
		keys = append(keys, k)
	}
	return keys, rows.Err()
}

func (q *Queries) GetSigningKeyByKID(ctx context.Context, kid string) (SigningKey, error) {
	row := q.db.QueryRow(ctx, `SELECT id, kid, algorithm, private_key_pem, public_key_pem, created_at, activated_at, retired_at, deleted_at FROM signing_keys WHERE kid = $1 AND deleted_at IS NULL`, kid)
	return scanSigningKey(row)
}

// scanner works for both pgx.Row and pgx.Rows
type scanner interface {
	Scan(dest ...any) error
}

func scanSigningKey(s scanner) (SigningKey, error) {
	var k SigningKey
	err := s.Scan(&k.ID, &k.Kid, &k.Algorithm, &k.PrivateKeyPem, &k.PublicKeyPem, &k.CreatedAt, &k.ActivatedAt, &k.RetiredAt, &k.DeletedAt)
	return k, err
}

func (q *Queries) RetireSigningKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, `UPDATE signing_keys SET retired_at = NOW() WHERE id = $1 AND retired_at IS NULL`, id)
	return err
}

func (q *Queries) DeleteRetiredSigningKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, `UPDATE signing_keys SET deleted_at = NOW() WHERE retired_at IS NOT NULL AND retired_at < NOW() - INTERVAL '30 minutes' AND deleted_at IS NULL`)
	return err
}

// ── Login Attempts ─────────────────────────────────────────────────────────

func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, `INSERT INTO login_attempts (id, email, success, ip_address, user_agent) VALUES ($1, $2, $3, $4, $5)`,
		arg.ID, arg.Email, arg.Success, arg.IPAddress, arg.UserAgent)
	return err
}

func (q *Queries) CountRecentFailedAttempts(ctx context.Context, email string) (int64, error) {
	var count int64
	err := q.db.QueryRow(ctx, `SELECT COUNT(*) FROM login_attempts WHERE email = $1 AND success = FALSE AND attempted_at > NOW() - INTERVAL '15 minutes'`, email).Scan(&count)
	return count, err
}

// ── Outbox ─────────────────────────────────────────────────────────────────

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, `INSERT INTO outbox (id, aggregate_id, event_type, payload) VALUES ($1, $2, $3, $4)`,
		arg.ID, arg.AggregateID, arg.EventType, arg.Payload)
	return err
}

func (q *Queries) GetUnpublishedEvents(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, `SELECT id, aggregate_id, event_type, payload, occurred_at, published_at FROM outbox WHERE published_at IS NULL ORDER BY occurred_at ASC LIMIT $1 FOR UPDATE SKIP LOCKED`, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var events []Outbox
	for rows.Next() {
		var e Outbox
		if err := rows.Scan(&e.ID, &e.AggregateID, &e.EventType, &e.Payload, &e.OccurredAt, &e.PublishedAt); err != nil {
			return nil, err
		}
		events = append(events, e)
	}
	return events, rows.Err()
}

func (q *Queries) MarkEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, `UPDATE outbox SET published_at = NOW() WHERE id = $1`, id)
	return err
}

// isNotFound returns true for pgx "no rows" errors.
func isNotFound(err error) bool {
	return errors.Is(err, pgx.ErrNoRows)
}

// Expose for repository layer.
var ErrNotFound = pgx.ErrNoRows

// Unused variable to satisfy the time import.
var _ = time.Now
