// Code generated by sqlc. DO NOT EDIT.
// Run `make generate` to regenerate.

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// Users
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error

	// Refresh tokens
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error
	DeleteExpiredTokens(ctx context.Context) error

	// Password reset
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error

	// Signing keys
	CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) (SigningKey, error)
	GetActiveSigningKey(ctx context.Context) (SigningKey, error)
	ListValidatingSigningKeys(ctx context.Context) ([]SigningKey, error)
	GetSigningKeyByKID(ctx context.Context, kid string) (SigningKey, error)
	RetireSigningKey(ctx context.Context, id uuid.UUID) error
	DeleteRetiredSigningKeys(ctx context.Context) error

	// Login attempts
	RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error
	CountRecentFailedAttempts(ctx context.Context, email string) (int64, error)

	// Outbox
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	GetUnpublishedEvents(ctx context.Context, limit int32) ([]Outbox, error)
	MarkEventPublished(ctx context.Context, id uuid.UUID) error

	// Personal access tokens
	CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) (PersonalAccessToken, error)
	GetPersonalAccessTokenByHash(ctx context.Context, tokenHash string) (PersonalAccessToken, error)
	ListPersonalAccessTokensByUser(ctx context.Context, userID uuid.UUID) ([]PersonalAccessToken, error)
	RevokePersonalAccessToken(ctx context.Context, arg RevokePersonalAccessTokenParams) error
	TouchPersonalAccessTokenLastUsed(ctx context.Context, id uuid.UUID) error
}

// Param structs

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

type UpdatePasswordHashParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

type CreateRefreshTokenParams struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UserAgent *string    `json:"user_agent"`
	IPAddress *string    `json:"ip_address"`
}

type RevokeRefreshTokenParams struct {
	ID         uuid.UUID  `json:"id"`
	ReplacedBy *uuid.UUID `json:"replaced_by"`
}

type CreatePasswordResetTokenParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

type CreateSigningKeyParams struct {
	ID            uuid.UUID `json:"id"`
	Kid           string    `json:"kid"`
	Algorithm     string    `json:"algorithm"`
	PrivateKeyPem string    `json:"private_key_pem"`
	PublicKeyPem  string    `json:"public_key_pem"`
}

type RecordLoginAttemptParams struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Success   bool      `json:"success"`
	IPAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
}

type InsertOutboxEventParams struct {
	ID          uuid.UUID `json:"id"`
	AggregateID uuid.UUID `json:"aggregate_id"`
	EventType   string    `json:"event_type"`
	Payload     []byte    `json:"payload"`
}

type CreatePersonalAccessTokenParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Name        string    `json:"name"`
	TokenHash   string    `json:"token_hash"`
	TokenPrefix string    `json:"token_prefix"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type RevokePersonalAccessTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}
